"""Structured meal-template database for the local meal-plan engine.

No OpenAI. Each template is a real, balanced, wellness-friendly meal with macros,
ingredients, prep steps, dietary patterns, and allergens — so the engine
(mealplan.py) filters by preference/allergies and scales to a calorie target.

Includes healthy, lower-calorie takes on Slavic / Russian classics (protein
syrniki, tvorog zapekanka, grechka bowls, vinegret, golubtsy,
borscht, plov) alongside everyday wellness meals. 14+ options per category.

diets tokens:    vegetarian | vegan | gluten_free | dairy_free | high_protein
allergen tokens: dairy | gluten | egg | soy | fish | shellfish | nuts
"""
from __future__ import annotations

DIET_FLAGS = {"vegetarian", "vegan", "gluten_free", "dairy_free", "high_protein"}


def _t(slot, title, desc, kcal, p, c, f, fiber, ingredients, steps, diets, allergens):
    diets = set(diets)
    if "vegan" in diets:
        diets.add("vegetarian")
    return {
        "slot": slot, "title": title, "description": desc,
        "kcal": kcal, "protein": p, "carbs": c, "fat": f, "fiber": fiber,
        "ingredients": [{"item": i, "grams": g} for i, g in ingredients],
        "steps": steps, "diets": diets, "allergens": set(allergens),
    }


TEMPLATES = [
    # ==================== BREAKFAST ====================
    _t("Breakfast", "Greek Yogurt & Berry Bowl", "Creamy high-protein yogurt with berries & oats.",
       320, 28, 38, 8, 6, [("Greek yogurt", 200), ("Mixed berries", 100), ("Rolled oats", 30), ("Honey", 10)],
       ["Spoon yogurt into a bowl.", "Top with berries, oats and a drizzle of honey."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy"}),
    _t("Breakfast", "Protein Syrniki", "Healthy tvorog (cottage cheese) pancakes — a Slavic classic.",
       330, 32, 28, 9, 2, [("Cottage cheese", 200), ("Egg", 50), ("Oat flour", 30), ("Honey", 8)],
       ["Mix cottage cheese, egg and oat flour into a batter.", "Form small patties, pan-fry on low heat until golden.", "Serve with a little honey or berries."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy", "egg"}),
    _t("Breakfast", "Protein Pancakes", "Fluffy oat & banana protein pancakes.",
       340, 28, 44, 7, 5, [("Oats", 45), ("Banana", 90), ("Egg", 50), ("Protein powder", 20)],
       ["Blend oats, banana, egg and protein powder.", "Cook small pancakes in a non-stick pan.", "Stack and top with berries."],
       {"vegetarian", "high_protein"}, {"egg"}),
    _t("Breakfast", "Tvorog Breakfast Bowl", "Cottage cheese with berries, honey & a little granola.",
       300, 30, 26, 8, 4, [("Cottage cheese", 200), ("Mixed berries", 80), ("Granola", 20), ("Honey", 8)],
       ["Spoon cottage cheese into a bowl.", "Top with berries, granola and honey."],
       {"vegetarian", "high_protein"}, {"dairy", "gluten"}),
    _t("Breakfast", "Cottage Cheese Zapekanka", "Baked tvorog casserole — light & high protein.",
       310, 30, 30, 7, 2, [("Cottage cheese", 200), ("Egg", 50), ("Semolina", 25), ("Raisins", 15)],
       ["Mix cottage cheese, egg, semolina and raisins.", "Bake at 180°C for 30 min until set and golden."],
       {"vegetarian", "high_protein"}, {"dairy", "egg", "gluten"}),
    _t("Breakfast", "Protein Overnight Oats", "Oats soaked with plant milk, protein & banana.",
       350, 30, 46, 8, 7, [("Rolled oats", 50), ("Plant milk", 200), ("Protein powder", 25), ("Banana", 80)],
       ["Mix oats, plant milk and protein powder in a jar.", "Refrigerate overnight, top with banana."],
       {"vegetarian", "dairy_free", "high_protein"}, set()),
    _t("Breakfast", "Tofu Veggie Scramble", "Savoury scrambled tofu with peppers & spinach.",
       300, 22, 14, 16, 5, [("Firm tofu", 180), ("Bell pepper", 60), ("Spinach", 40), ("Olive oil", 8)],
       ["Crumble tofu into a hot oiled pan.", "Add peppers and spinach, season with turmeric & salt."],
       {"vegan", "gluten_free", "dairy_free", "high_protein"}, {"soy"}),
    _t("Breakfast", "Avocado Toast & Eggs", "Sourdough, smashed avocado & two soft eggs.",
       380, 18, 32, 22, 8, [("Sourdough bread", 60), ("Avocado", 80), ("Eggs", 100), ("Cherry tomatoes", 50)],
       ["Toast the bread.", "Smash avocado on top.", "Add poached or fried eggs and tomatoes."],
       {"vegetarian"}, {"gluten", "egg"}),
    _t("Breakfast", "Egg White Veggie Omelette", "Light, fluffy omelette packed with vegetables.",
       260, 28, 8, 12, 3, [("Egg whites", 200), ("Whole egg", 50), ("Spinach", 40), ("Tomato", 50)],
       ["Whisk egg whites with one whole egg.", "Pour into a hot pan with veg, fold and cook through."],
       {"vegetarian", "gluten_free", "dairy_free", "high_protein"}, {"egg"}),
    _t("Breakfast", "Buckwheat Porridge", "Warm grechka simmered in milk — comforting & balanced.",
       320, 14, 52, 7, 8, [("Buckwheat", 60), ("Milk", 200), ("Honey", 10), ("Berries", 50)],
       ["Simmer buckwheat in milk until soft.", "Sweeten lightly and top with berries."],
       {"vegetarian", "gluten_free"}, {"dairy"}),
    _t("Breakfast", "High-Protein Rye Toast", "Rye toast with whipped cottage cheese & tomato.",
       300, 24, 34, 8, 6, [("Rye bread", 60), ("Cottage cheese", 120), ("Tomato", 60), ("Chives", 5)],
       ["Toast rye bread.", "Spread whipped cottage cheese, top with tomato and chives."],
       {"vegetarian", "high_protein"}, {"dairy", "gluten"}),
    _t("Breakfast", "Banana Protein Smoothie", "Quick creamy protein smoothie.",
       300, 30, 38, 5, 4, [("Protein powder", 30), ("Banana", 100), ("Milk", 200), ("Peanut butter", 8)],
       ["Blend everything until smooth.", "Serve cold."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy", "nuts"}),
    _t("Breakfast", "Baked Apple-Cinnamon Oats", "Cosy baked oats with apple & cinnamon.",
       330, 10, 54, 8, 8, [("Rolled oats", 60), ("Plant milk", 180), ("Apple", 100), ("Cinnamon", 2)],
       ["Mix oats, milk, diced apple and cinnamon.", "Bake at 180°C for 25 min."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Breakfast", "Chia Pudding & Berries", "Coconut chia pudding topped with fresh berries.",
       320, 10, 34, 16, 12, [("Chia seeds", 40), ("Coconut milk", 200), ("Mixed berries", 80), ("Maple syrup", 10)],
       ["Stir chia into coconut milk with maple syrup.", "Chill overnight, top with berries."],
       {"vegan", "gluten_free", "dairy_free"}, set()),

    # ==================== LUNCH ====================
    _t("Lunch", "Grilled Chicken & Quinoa Bowl", "Lean chicken, fluffy quinoa & roasted veg.",
       480, 42, 45, 14, 8, [("Chicken breast", 150), ("Quinoa", 70), ("Roasted veg", 120), ("Olive oil", 10)],
       ["Cook quinoa.", "Grill seasoned chicken.", "Assemble with roasted veg."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Lunch", "Buckwheat & Chicken Bowl", "Grechka with grilled chicken and vegetables.",
       470, 40, 48, 12, 9, [("Buckwheat", 70), ("Chicken breast", 140), ("Mixed veg", 100), ("Olive oil", 8)],
       ["Cook buckwheat.", "Grill chicken, sauté veg.", "Combine and season."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Lunch", "Salmon & Greens Salad", "Omega-rich salmon over a crisp leafy salad.",
       450, 35, 18, 26, 6, [("Salmon fillet", 130), ("Mixed greens", 100), ("Avocado", 50), ("Olive oil", 12)],
       ["Sear or bake salmon.", "Toss greens with oil and lemon, top with salmon."],
       {"gluten_free", "dairy_free", "high_protein"}, {"fish"}),
    _t("Lunch", "Vinegret with Chickpeas", "Slavic beet salad boosted with chickpeas.",
       420, 16, 58, 14, 14, [("Beetroot", 120), ("Potato", 80), ("Chickpeas", 100), ("Olive oil", 12)],
       ["Dice boiled beet, potato and carrot.", "Mix with chickpeas, pickles and oil."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Lunch", "Mediterranean Chickpea Bowl", "Chickpeas, cucumber, tomato & herbed dressing.",
       460, 18, 60, 16, 14, [("Chickpeas", 150), ("Cucumber", 80), ("Cherry tomatoes", 80), ("Olive oil", 12)],
       ["Combine chickpeas and veg.", "Dress with oil, lemon and herbs."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Lunch", "Turkey & Avocado Wrap", "Lean turkey, avocado & salad in a wrap.",
       470, 36, 40, 18, 7, [("Whole-wheat wrap", 60), ("Turkey breast", 120), ("Avocado", 50), ("Salad leaves", 40)],
       ["Layer turkey, avocado and leaves.", "Roll tightly and slice."],
       {"dairy_free", "high_protein"}, {"gluten"}),
    _t("Lunch", "Chicken & Vegetable Soup", "Light, nourishing broth with chicken and veg.",
       360, 34, 28, 10, 6, [("Chicken breast", 130), ("Mixed vegetables", 150), ("Potato", 80), ("Herbs", 5)],
       ["Simmer chicken with vegetables and potato.", "Season with herbs and serve hot."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Lunch", "Tofu Teriyaki Rice Bowl", "Glazed tofu with rice & steamed greens.",
       450, 24, 58, 12, 7, [("Firm tofu", 150), ("Cooked rice", 150), ("Broccoli", 80), ("Teriyaki sauce", 20)],
       ["Pan-fry tofu, glaze with teriyaki.", "Serve over rice with broccoli."],
       {"vegan", "gluten_free", "dairy_free", "high_protein"}, {"soy"}),
    _t("Lunch", "Lentil & Veg Stew", "Hearty, fibre-rich lentil stew.",
       430, 22, 60, 9, 16, [("Lentils", 150), ("Carrot", 60), ("Tomato", 80), ("Onion", 40)],
       ["Sauté onion and carrot.", "Add lentils and tomato, simmer until soft."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Lunch", "Shrimp & Quinoa Salad", "Light protein-packed shrimp salad.",
       420, 34, 40, 12, 7, [("Shrimp", 130), ("Quinoa", 60), ("Cucumber", 80), ("Olive oil", 10)],
       ["Cook quinoa and shrimp.", "Toss with cucumber, lemon and oil."],
       {"gluten_free", "dairy_free", "high_protein"}, {"shellfish"}),
    _t("Lunch", "Tuna & White Bean Salad", "Protein-rich, no-cook lunch.",
       430, 36, 34, 16, 10, [("Tuna", 120), ("White beans", 120), ("Red onion", 30), ("Olive oil", 12)],
       ["Drain tuna and beans.", "Toss with onion, lemon and oil."],
       {"gluten_free", "dairy_free", "high_protein"}, {"fish"}),
    _t("Lunch", "Cottage Cheese Tartine", "Open rye sandwich with whipped tvorog & cucumber.",
       380, 26, 40, 10, 6, [("Rye bread", 70), ("Cottage cheese", 130), ("Cucumber", 60), ("Dill", 5)],
       ["Spread whipped cottage cheese on rye.", "Top with cucumber and dill."],
       {"vegetarian", "high_protein"}, {"dairy", "gluten"}),
    _t("Lunch", "Baked Cod & Roasted Veg", "Flaky cod with a tray of roasted vegetables.",
       420, 38, 30, 14, 8, [("Cod fillet", 160), ("Mixed vegetables", 180), ("Olive oil", 10), ("Lemon", 20)],
       ["Bake cod with lemon.", "Roast vegetables alongside and plate."],
       {"gluten_free", "dairy_free", "high_protein"}, {"fish"}),

    # ==================== SNACK ====================
    _t("Snack", "Vanilla Protein Shake", "Quick high-protein shake to bridge meals.",
       200, 25, 12, 4, 1, [("Protein powder", 30), ("Plant milk", 250)],
       ["Blend protein powder with milk and ice."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy"}),
    _t("Snack", "Tvorog with Berries", "Cottage cheese topped with fresh berries.",
       180, 20, 14, 4, 3, [("Cottage cheese", 150), ("Mixed berries", 60)],
       ["Top cottage cheese with berries and a little honey."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy"}),
    _t("Snack", "Protein Syrniki Bites", "Mini baked cottage-cheese bites.",
       210, 22, 18, 6, 1, [("Cottage cheese", 130), ("Egg", 40), ("Oat flour", 20)],
       ["Mix, form bites, bake at 180°C for 18 min."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy", "egg"}),
    _t("Snack", "No-Bake Protein Cheesecake Cup", "Whipped tvorog cheesecake — wellness dessert.",
       220, 24, 18, 6, 1, [("Cottage cheese", 150), ("Greek yogurt", 50), ("Honey", 10), ("Berries", 40)],
       ["Blend cottage cheese, yogurt and honey until smooth.", "Chill and top with berries."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy"}),
    _t("Snack", "Kefir & Berry Smoothie", "Probiotic kefir blended with berries.",
       180, 14, 24, 3, 3, [("Kefir", 250), ("Mixed berries", 80)],
       ["Blend kefir with berries until smooth."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy"}),
    _t("Snack", "Greek Yogurt & Honey", "Simple high-protein yogurt snack.",
       180, 18, 20, 3, 0, [("Greek yogurt", 170), ("Honey", 12)],
       ["Stir honey through Greek yogurt."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy"}),
    _t("Snack", "Boiled Eggs & Cucumber", "Two eggs with crunchy cucumber.",
       180, 14, 4, 11, 1, [("Eggs", 100), ("Cucumber", 100)],
       ["Boil eggs.", "Serve with sliced cucumber and pepper."],
       {"vegetarian", "gluten_free", "dairy_free", "high_protein"}, {"egg"}),
    _t("Snack", "Apple & Almond Butter", "Crunchy apple slices with almond butter.",
       220, 6, 26, 12, 6, [("Apple", 150), ("Almond butter", 20)],
       ["Slice apple and serve with almond butter."],
       {"vegan", "gluten_free", "dairy_free"}, {"nuts"}),
    _t("Snack", "Hummus & Veggie Sticks", "Creamy hummus with crudités.",
       190, 8, 22, 8, 7, [("Hummus", 80), ("Carrot", 80), ("Cucumber", 80)],
       ["Serve veg sticks with hummus."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Snack", "Cottage Cheese & Rice Cakes", "High-protein cottage cheese on rice cakes.",
       200, 18, 24, 3, 1, [("Cottage cheese", 120), ("Rice cakes", 30), ("Cucumber", 40)],
       ["Spread cottage cheese on rice cakes, top with cucumber."],
       {"vegetarian", "gluten_free", "high_protein"}, {"dairy"}),
    _t("Snack", "Roasted Chickpeas", "Crispy spiced chickpeas.",
       190, 10, 28, 5, 8, [("Chickpeas", 120), ("Olive oil", 6), ("Spices", 2)],
       ["Toss chickpeas in oil and spices.", "Roast at 200°C until crisp."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Snack", "Edamame", "Steamed soy beans with sea salt.",
       180, 17, 14, 8, 8, [("Edamame", 150), ("Sea salt", 1)],
       ["Steam edamame.", "Sprinkle with sea salt."],
       {"vegan", "gluten_free", "dairy_free", "high_protein"}, {"soy"}),
    _t("Snack", "Rice Cakes & Nut Butter", "Light rice cakes with nut butter.",
       210, 7, 28, 9, 3, [("Rice cakes", 30), ("Peanut butter", 18), ("Banana", 50)],
       ["Spread nut butter on rice cakes, top with banana."],
       {"vegan", "gluten_free", "dairy_free"}, {"nuts"}),
    _t("Snack", "Dark Chocolate & Almonds", "A little dark chocolate with almonds.",
       200, 6, 16, 14, 4, [("Dark chocolate", 20), ("Almonds", 20)],
       ["Enjoy dark chocolate with a small handful of almonds."],
       {"vegan", "gluten_free", "dairy_free"}, {"nuts"}),

    # ==================== DINNER ====================
    _t("Dinner", "Lean Steak & Sweet Potato", "Seared lean steak with roasted sweet potato.",
       520, 44, 40, 18, 7, [("Lean steak", 160), ("Sweet potato", 180), ("Green beans", 90), ("Olive oil", 8)],
       ["Roast sweet potato.", "Sear steak, rest 5 min.", "Serve with green beans."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Dinner", "Light Golubtsy", "Lighter cabbage rolls with turkey & rice.",
       450, 36, 38, 16, 8, [("Turkey mince", 150), ("Cabbage", 120), ("Rice", 60), ("Tomato", 80)],
       ["Wrap turkey-rice filling in blanched cabbage leaves.", "Simmer in light tomato sauce until cooked."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Dinner", "Turkey Meatballs & Buckwheat", "Lean meatballs over fluffy grechka.",
       480, 42, 44, 14, 8, [("Turkey mince", 150), ("Buckwheat", 70), ("Tomato sauce", 80), ("Onion", 30)],
       ["Bake seasoned turkey meatballs.", "Serve over buckwheat with tomato sauce."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Dinner", "Baked Salmon & Asparagus", "Herby baked salmon with asparagus.",
       480, 40, 16, 28, 6, [("Salmon fillet", 150), ("Asparagus", 120), ("Olive oil", 12), ("Lemon", 20)],
       ["Bake salmon with lemon.", "Roast asparagus alongside."],
       {"gluten_free", "dairy_free", "high_protein"}, {"fish"}),
    _t("Dinner", "Chicken & Roasted Veg", "Herb chicken with a tray of roasted vegetables.",
       480, 42, 34, 16, 9, [("Chicken breast", 160), ("Mixed vegetables", 200), ("Olive oil", 10)],
       ["Roast vegetables.", "Add seasoned chicken and roast until cooked."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Dinner", "Chicken Plov (Light)", "Lighter plov with brown rice & lean chicken.",
       500, 38, 56, 14, 6, [("Chicken breast", 140), ("Brown rice", 80), ("Carrot", 80), ("Onion", 40)],
       ["Sauté onion and carrot.", "Add chicken and rice with stock, simmer until done."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Dinner", "Stuffed Peppers", "Peppers filled with turkey & rice.",
       460, 36, 42, 14, 8, [("Bell peppers", 160), ("Turkey mince", 130), ("Rice", 60), ("Tomato", 60)],
       ["Fill peppers with turkey-rice mix.", "Bake at 190°C for 35 min."],
       {"gluten_free", "dairy_free", "high_protein"}, set()),
    _t("Dinner", "Tofu Buddha Bowl", "Roasted tofu, grains & rainbow veg.",
       470, 24, 52, 18, 12, [("Firm tofu", 150), ("Quinoa", 120), ("Roasted veg", 120), ("Tahini", 15)],
       ["Roast tofu.", "Assemble over quinoa with veg and tahini."],
       {"vegan", "gluten_free", "dairy_free", "high_protein"}, {"soy"}),
    _t("Dinner", "Light Borscht with Beans", "Vibrant beet soup, plant-protein boosted.",
       380, 16, 52, 8, 12, [("Beetroot", 120), ("Cabbage", 100), ("White beans", 100), ("Tomato", 60)],
       ["Simmer beet, cabbage and tomato.", "Add beans, season, finish with a little yogurt if desired."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Dinner", "Veggie Chili & Rice", "Hearty bean chili over rice.",
       460, 20, 66, 10, 16, [("Mixed beans", 180), ("Chopped tomatoes", 120), ("Rice", 120), ("Onion", 40)],
       ["Sauté onion, add beans, tomatoes and spices.", "Simmer and serve over rice."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
    _t("Dinner", "Baked White Fish & Quinoa", "Light white fish with lemony quinoa.",
       440, 38, 38, 12, 7, [("White fish fillet", 160), ("Quinoa", 70), ("Courgette", 100), ("Olive oil", 8)],
       ["Bake fish with herbs.", "Serve over quinoa with sautéed courgette."],
       {"gluten_free", "dairy_free", "high_protein"}, {"fish"}),
    _t("Dinner", "Shrimp Veg Stir-fry", "Quick shrimp & vegetable stir-fry.",
       400, 36, 30, 14, 6, [("Shrimp", 150), ("Mixed stir-fry veg", 180), ("Rice", 50), ("Sesame oil", 8)],
       ["Stir-fry shrimp and veg.", "Toss with a little rice and sesame oil."],
       {"gluten_free", "dairy_free", "high_protein"}, {"shellfish"}),
    _t("Dinner", "Baked Draniki & Salmon", "Baked potato pancakes with smoked salmon.",
       460, 30, 44, 18, 6, [("Grated potato", 200), ("Egg", 50), ("Smoked salmon", 80), ("Dill", 5)],
       ["Bake seasoned potato pancakes until golden.", "Top with smoked salmon and dill."],
       {"gluten_free", "dairy_free", "high_protein"}, {"egg", "fish"}),
    _t("Dinner", "Eggplant & Chickpea Bake", "Mediterranean veg bake, fibre-rich.",
       430, 18, 56, 14, 14, [("Eggplant", 180), ("Chickpeas", 120), ("Tomato", 100), ("Olive oil", 12)],
       ["Layer eggplant, chickpeas and tomato.", "Bake at 190°C for 30 min."],
       {"vegan", "gluten_free", "dairy_free"}, set()),
]


def templates_for(slot: str):
    return [t for t in TEMPLATES if t["slot"] == slot]
