"""Daily Motivation library — 365+ unique, premium, identity-based messages.

No OpenAI, no API calls, no per-message cost. A deterministic daily rotation
(by day-of-year, offset per user so two people don't always see the same line)
means every user gets a fresh, non-generic message every day for a full year.

Tone: luxury wellness, transformation, self-respect, the unseen work, promises
kept to yourself. Never generic ("keep going"), never medical, never a weight
promise.
"""
from __future__ import annotations

import datetime

MESSAGES = [
    # --- identity & becoming ---
    "The version of you that you're dreaming about is being built by today's decisions.",
    "You're not starting over. You're starting from experience.",
    "You don't rise to the body you want — you fall to the habits you keep.",
    "Become the kind of woman your habits would predict.",
    "You're one decision away from acting like the person you're becoming.",
    "Stop waiting to feel like her. Start behaving like her.",
    "Identity first, results second. Decide who you are, then prove it daily.",
    "The woman you're becoming is watching how you treat today.",
    "You're not trying to change your body. You're trying to change your self-image.",
    "Every healthy choice is a quiet vote for the woman you're becoming.",
    "She didn't find motivation. She built a standard.",
    "You already are her on the inside. The outside is just catching up.",
    "The goal was never the body. It was becoming someone who keeps her word.",
    "Act like the woman who already has what you want.",
    "Confidence isn't given to you. You build it one kept promise at a time.",
    "You're allowed to become someone your past self wouldn't recognize.",
    "Your future self is formed in the choices nobody applauds.",
    "Be loyal to your future, not your comfort.",
    "The strongest version of you is built in ordinary moments.",
    "You're not behind. You're in the part of the story before it gets good.",
    "Decide she exists, then spend your days agreeing with her.",
    "The body follows the identity. Change who you are, and the rest follows.",
    "You don't need a new you. You need to stop abandoning the one you're building.",
    "Greatness is just your normal, upgraded a little every day.",
    "You become unstoppable the moment you stop negotiating with yourself.",
    "The real glow-up is internal. The mirror just reports it later.",
    "You're not the woman who gives up. That's an old version of you.",
    "Build the self-respect first. The body is a side effect.",
    "Every day you show up, you become harder to disappoint.",
    "She is not lucky. She is consistent.",

    # --- consistency over intensity ---
    "Most people stop right before the results appear. Consistency is where transformation begins.",
    "One healthy meal never changes a body. Hundreds of small decisions do.",
    "Consistency is just love for your future self, repeated daily.",
    "You don't need a perfect week. You need an unbroken direction.",
    "Small actions, repeated, become the body you stop having to think about.",
    "The boring days are the ones that build you.",
    "Motivation starts it. Consistency finishes it.",
    "Show up on the day you least feel like it — that day counts double.",
    "Your results live on the other side of the days you wanted to quit.",
    "Average effort, applied daily, beats brilliance applied once.",
    "Don't chase intensity. Chase the streak you refuse to break.",
    "The magic isn't in one decision. It's in the thousandth.",
    "Repetition is the most underrated beauty secret there is.",
    "Steady is sexy. Steady is what wins.",
    "You can't hate yourself into consistency. You can only respect yourself into it.",
    "A little, every day, beats a lot, never.",
    "Discipline is choosing between what you want now and what you want most.",
    "Make showing up so normal it stops feeling like effort.",
    "The compound interest of small habits is staggering. Just keep depositing.",
    "Done consistently beats done perfectly, every single time.",
    "You're not failing. You're just early in the compounding.",
    "Be relentless about the basics and the rest takes care of itself.",
    "Consistency turns motivation into momentum, and momentum into identity.",
    "Win the day, then do it again. That's the whole secret.",
    "The plan only works if you do — gently, repeatedly, on purpose.",
    "Your habits are voting for your future every single day. Keep them honest.",
    "Quietly consistent women become loudly successful ones.",
    "Don't break the chain. Future you is counting the links.",
    "Results are rented, not owned. Consistency is the rent.",
    "Keep the promise small enough to keep, then keep it forever.",

    # --- the unseen work ---
    "The body you want is built when nobody is watching.",
    "Discipline is what you do when the excitement wears off.",
    "Nobody sees the salad. Everybody sees the glow.",
    "The work that changes you is rarely the work anyone claps for.",
    "Private discipline becomes public confidence.",
    "What you do in the quiet decides what you become in the open.",
    "The glow is just a hundred unseen 'no thank yous' wearing a smile.",
    "You're building something real in the moments no one will ever know about.",
    "Champions are made in the reps nobody counts.",
    "Your discipline whispers now. One day it will be impossible to ignore.",
    "The unglamorous choice today is the glamorous result later.",
    "She kept going when it was boring. That's the entire difference.",
    "What looks like luck is usually just unwitnessed consistency.",
    "The version of you that gives up never gets to see what was coming.",
    "Show up for yourself even when there's no audience.",
    "The hardest reps are the ones nobody asked you to do.",
    "Your standards in private decide your results in public.",
    "Beauty maintained quietly outlasts beauty announced loudly.",
    "Do the small thing well, especially when it doesn't feel like it matters.",
    "Earn your reflection in the moments only you witness.",

    # --- promises to yourself ---
    "Your confidence grows every time you keep a promise to yourself.",
    "Self-trust is built one tiny kept promise at a time.",
    "Stop breaking promises to the one person who can't leave you — you.",
    "Keep the appointment with yourself. You're worth showing up for.",
    "Every promise you keep to yourself rewrites what you believe you're capable of.",
    "The relationship that changes everything is the one you have with your word.",
    "Be the kind of woman who does what she said she would.",
    "You don't need more discipline. You need to stop letting yourself off the hook.",
    "Honor the plan you made when you were inspired.",
    "Trust isn't built in big moments. It's built in kept-small ones.",
    "When you keep promises to yourself, your self-belief stops needing proof.",
    "Loyalty starts at home — with the goals you set for yourself.",
    "The most attractive thing you can build is integrity with yourself.",
    "Each kept commitment is a brick in the woman you're becoming.",
    "Don't let a hard day make a liar out of you.",
    "Show yourself you mean it. Then show yourself again tomorrow.",
    "You become powerful the moment your word to yourself becomes law.",
    "Keep going so your future self can finally trust you.",
    "A promise kept quietly is worth more than a goal announced loudly.",
    "Reliability to yourself is the foundation of every transformation.",

    # --- small decisions ---
    "Greatness hides inside boring, repeated choices.",
    "The next small decision is more powerful than the big plan.",
    "You're always one choice away from a completely different momentum.",
    "Tiny choices are not tiny. They're the architecture of your life.",
    "Choose the slightly better option. Do it again in an hour.",
    "Your day is a series of small votes. Make most of them count.",
    "The little decision you're avoiding is the one that matters.",
    "Win the next choice, not the whole month.",
    "Big transformations are just small decisions that refused to stop.",
    "What you do next matters more than what you did last.",
    "One better choice doesn't transform you. The habit of better choices does.",
    "You can restart your standards at the very next meal.",
    "The smallest healthy decision still moves you in the right direction.",
    "Stack good choices like coins. The pile becomes undeniable.",
    "A single 'yes' to yourself can redirect an entire day.",
    "Make the choice your future self would high-five you for.",
    "Don't underestimate the power of doing the obvious thing on purpose.",
    "Every meal is a fresh chance to vote for the woman you're becoming.",
    "The difference between who you are and who you want to be is your next choice.",
    "Choose well now. Compound it later.",

    # --- confidence & self-worth ---
    "Your worth was never up for negotiation with a number.",
    "Confidence is a muscle. Every kept habit is a rep.",
    "You don't earn the right to feel good about yourself. You decide it, then back it up.",
    "Carry yourself like the transformation already started — because it has.",
    "Self-respect looks good on you. Wear it daily.",
    "You're allowed to be proud of yourself before anyone else notices.",
    "Confidence isn't a look. It's the evidence of promises kept.",
    "Stand taller. You've been showing up for yourself.",
    "The most magnetic thing about you is how you treat you.",
    "You don't have to earn rest, kindness, or pride. Take them.",
    "Speak to yourself like someone you're proud to be becoming.",
    "Your value isn't on the scale. It's in your standards.",
    "Walk like a woman who keeps her own promises — because you do.",
    "Confidence is quiet self-trust that stopped needing applause.",
    "You are not a project to fix. You are a person to back.",
    "Believe in the effort. The results are just the receipt.",
    "Glow comes from how you feel about how you're living.",
    "Be your own standard. Stop auditioning for everyone else's.",
    "You're becoming someone you'd admire. Let that land.",
    "Hold your head up — discipline is the best accessory you own.",

    # --- patience & trust the process ---
    "Your future self will thank you for today's quiet effort.",
    "Trust the process you can't see results from yet.",
    "Growth is happening even on the days it feels invisible.",
    "The seed doesn't argue with the soil about timing.",
    "You're not stuck. You're rooting before you bloom.",
    "Be patient with a body that's been patient with you.",
    "Results love women who stop demanding them daily.",
    "Slow progress is still you lapping the version that quit.",
    "What feels like nothing is often everything, just early.",
    "Give it time the way you'd give a friend time.",
    "The harvest is coming. Keep tending the rows.",
    "You can't rush a transformation, but you can refuse to abandon it.",
    "Trust that consistency is working even before it's visible.",
    "Progress is rarely loud. Keep listening for the quiet wins.",
    "The body keeps score of every kind, steady choice.",
    "Don't dig up the seed to check if it's growing. Keep watering.",
    "Patience is just confidence with a longer timeline.",
    "The plateau is the part where the work goes underground.",
    "Stay in the process long enough to become unrecognizable.",
    "Time rewards the woman who refuses to quit on herself.",

    # --- showing up / momentum ---
    "Showing up is the habit. Everything else is detail.",
    "Momentum is built on the days you almost didn't.",
    "You don't need to feel ready. You need to begin.",
    "Half-effort on a hard day still keeps the streak alive.",
    "Start before the motivation arrives. It catches up.",
    "The hardest step is the one out the door — take it anyway.",
    "Energy follows action, not the other way around.",
    "Begin badly if you must, but begin.",
    "Momentum doesn't care how you feel. It cares that you moved.",
    "One small action right now beats a perfect plan later.",
    "Keep the streak alive, even if today is just a flicker.",
    "Doing it tired still counts. Doing it busy still counts.",
    "You can be unmotivated and consistent at the same time.",
    "Action is the antidote to the day you don't feel like it.",
    "The momentum you build today carries the days you'll struggle.",
    "Just open the app, just log the meal, just take the step.",
    "Don't break the streak over a feeling.",
    "Move first. Mood improves second.",
    "Small and steady keeps the flywheel turning.",
    "You're always one rep away from feeling like yourself again.",

    # --- comparison & your own race ---
    "Comparison is the thief of every glow. Run your own race.",
    "Her chapter twenty is not your chapter two.",
    "The only body to compare yourself to is yesterday's habits.",
    "Stay in your lane. It's the only one going to your destination.",
    "Your progress doesn't need a witness to be real.",
    "Someone else's highlight reel is not your measuring stick.",
    "Compete with who you were last week, and nobody else.",
    "Eyes on your own plate. Your journey is custom-built.",
    "You're not behind. You're on a different, perfectly valid timeline.",
    "Envy fades the moment you focus on your own consistency.",
    "Be inspired by others, but measured only against yourself.",
    "The grass is greener where you water it — water yours.",
    "Your pace is the right pace because it's yours.",
    "Stop racing strangers. Start lapping your old habits.",
    "Comparison shrinks you. Self-focus expands you.",
    "Run quietly, improve constantly, compare rarely.",
    "There's no finish line you share with anyone else.",
    "Celebrate her wins, then get back to building yours.",
    "You're exactly where your effort has earned you to be — keep earning.",
    "Your only rival is the version of you who settles.",

    # --- resilience & restart ---
    "A missed day is data, not a verdict.",
    "You're never one bad meal away from ruin, only one good choice from restart.",
    "Falling off isn't failure. Staying off is.",
    "Restart at the next meal, not next Monday.",
    "Perfection was never the assignment. Persistence was.",
    "One off day can't undo a hundred good ones.",
    "Come back quickly. The streak forgives a quick return.",
    "Grace, then back to work. That's how the strong recover.",
    "You don't have to be perfect to be unstoppable.",
    "Setbacks are setups for the comeback you'll be proud of.",
    "The slip isn't the problem. The spiral is. Skip the spiral.",
    "Drop the guilt. Pick the next good choice instead.",
    "Resilience is just restarting faster than you fall.",
    "You're allowed to begin again as many times as it takes.",
    "A pause is not a quit. Press play.",
    "The strongest women are just the best at restarting.",
    "Yesterday's slip has no authority over today's choice.",
    "Bounce back before the story you tell yourself sets in.",
    "Mistakes are tuition. Pay it and keep learning.",
    "Get up so quickly that falling stops feeling like an option.",

    # --- self-love & gentleness ---
    "Treat your body like a partner, not a project.",
    "Speak to yourself the way you'd speak to your best friend.",
    "Rest is not a reward you earn. It's a need you honor.",
    "You can pursue change and accept yourself at the same time.",
    "Be gentle with the body carrying you through this.",
    "Care for yourself like someone worth caring for — because you are.",
    "Nourish, don't punish. Build, don't shrink.",
    "Your body hears everything your mind says. Be kind.",
    "Self-love is choosing your long-term wellbeing again and again.",
    "You deserve the same patience you give everyone else.",
    "Kindness to yourself is not softness. It's strategy.",
    "Feed your body like you actually like her.",
    "Grace over guilt. Always.",
    "You're allowed to be proud of how far you've come.",
    "Tend to yourself. You're the one home you'll always live in.",
    "Health is an act of self-respect, not self-punishment.",
    "Be the safe, encouraging voice you needed all along.",
    "Loving yourself and improving yourself are the same project.",
    "Give your body credit for everything it does without applause.",
    "Soften the inner critic. She was never the one who got you here.",

    # --- mindset & standards ---
    "Raise your standards and your habits will rise to meet them.",
    "Your mind is the first body part you train each day.",
    "Decide who you are on the hard days — that's your real identity.",
    "Standards beat motivation because standards don't need a mood.",
    "Think in identity, not in punishment.",
    "What you tolerate, you become. Tolerate excellence in small things.",
    "Set the bar where your future self lives.",
    "Your self-talk is the coaching you get most often. Make it good.",
    "Mindset is the multiplier on every habit you build.",
    "Choose the thought that builds you, not the one that shrinks you.",
    "Hold a standard, not a streak of self-criticism.",
    "Discipline is self-respect translated into action.",
    "Upgrade your inner dialogue and watch your habits follow.",
    "You don't need permission to expect more from your day.",
    "The story you tell yourself becomes the body you live in.",
    "Decide it's already who you are, then refuse to argue.",
    "Standards are kindness with a backbone.",
    "Your future is shaped by the questions you ask yourself daily.",
    "Be the woman with quietly impossible standards for her own care.",
    "Mindset first. The plan is just paperwork.",

    # --- energy, glow & vitality ---
    "Eat in a way that makes tomorrow's you feel powerful.",
    "Glow is just consistency wearing your face.",
    "Fuel your body for the life you're trying to build.",
    "Energy is the real luxury. Protect it like one.",
    "The way you eat today is the energy you spend tomorrow.",
    "Hydrate like your glow depends on it — because it partly does.",
    "Choose foods that make you feel awake, not heavy.",
    "Your vitality is your signature. Invest in it daily.",
    "Light meals, clear mind, steady energy — that's the goal.",
    "Build days that leave you energized, not depleted.",
    "Real beauty is just health you can see.",
    "Feed the glow. It's hungry for water, protein, and rest.",
    "How you feel is the truest mirror you own.",
    "Steady energy is a habit, not a personality trait.",
    "Nourishment is the most luxurious thing you can give yourself.",
    "Your skin, your sleep, your mood — all listening to today's choices.",
    "Trade the heavy comfort for the light kind that lasts.",
    "Glow is an inside job with outside benefits.",
    "Eat like a woman who plans to feel incredible at 3pm.",
    "Vitality is the quiet flex of a well-cared-for woman.",

    # --- courage & beginning ---
    "Courage is just doing it scared and doing it anyway.",
    "The beginning is always the bravest part. You already started.",
    "It's never too late to become who you could have been.",
    "Brave is not the absence of doubt. It's moving with it.",
    "Start ugly. Refine later. Just start.",
    "The leap is scary; the regret of not leaping is scarier.",
    "You don't need certainty to begin. You need willingness.",
    "Be brave enough to be a beginner again.",
    "The first step rarely feels ready. Take it anyway.",
    "Courage compounds. The next brave choice gets easier.",
    "Do the thing your future self is begging you to start.",
    "Bravery is a decision, not a feeling.",
    "You're more capable than your comfort zone wants you to believe.",
    "Begin where you are, with what you have, scared as you feel.",
    "The brave choice and the right choice are usually the same one.",
    "Fear shrinks when you walk toward it.",
    "Be bold enough to bet on your own consistency.",
    "Courage today buys confidence tomorrow.",
    "Starting is the hardest rep. You already did it.",
    "Dare to take yourself seriously.",

    # --- discipline & freedom ---
    "Discipline today is freedom tomorrow.",
    "The structure you resist is the freedom you crave.",
    "Discipline is choosing what you want most over what you want now.",
    "Freedom isn't doing whatever you feel. It's becoming who you decided to be.",
    "Self-discipline is the highest form of self-care.",
    "The disciplined version of you has the most options.",
    "Boundaries with yourself are the price of the body you want.",
    "Discipline isn't restriction. It's direction.",
    "Do the hard thing now so the rest of your life gets easier.",
    "Willpower is a muscle. Train it like one.",
    "The discipline you build today spends itself as confidence later.",
    "Freedom is fewer decisions because your habits already decided.",
    "Make discipline a love language to your future self.",
    "Structure is the scaffolding your glow-up is built on.",
    "The most free women are the most disciplined ones.",
    "Choose the habit, even when the mood disagrees.",
    "Discipline is just remembering what you really want.",
    "Comfort is a lovely cage. Discipline is the key.",
    "Earn your ease through your effort.",
    "Hard choices, easy life. Easy choices, hard life.",

    # --- gratitude, joy & the journey ---
    "Fall in love with the process and the results stop being the point.",
    "Enjoy becoming her. The arrival is brief; the becoming is the gift.",
    "Gratitude for your body accelerates the care you give it.",
    "Make the journey beautiful, not just the destination.",
    "Celebrate the small wins loudly enough to keep going.",
    "Joy is fuel. Find it in the daily showing-up.",
    "Be thankful for a body willing to change with you.",
    "The journey is the transformation. The body is the souvenir.",
    "Romanticize your healthy habits until they feel like luxury.",
    "Notice how far you've come before you measure how far is left.",
    "Appreciate the discipline; it's love in work clothes.",
    "Find delight in the ordinary act of caring for yourself.",
    "Gratitude turns enough into abundance, and effort into joy.",
    "Savor the becoming. You only get this chapter once.",
    "Make the daily ritual something you actually look forward to.",
    "The pride you feel tonight is worth more than the comfort you skipped.",
    "Treat your progress like a story worth telling.",
    "Joyful consistency outlasts grim discipline every time.",
    "Be glad you're someone who tries. That's already rare.",
    "Let the journey feel like a glow-up, not a grind.",

    # --- future self & vision ---
    "Live today like you've already met your future self and made her a promise.",
    "Your future self is formed by the choices your present self almost skips.",
    "Picture her clearly, then spend your day agreeing with her.",
    "The future you want is built from the boring parts of today.",
    "Behave like someone your future self would be proud to have been.",
    "Your next 90 days are a letter to the woman you're becoming.",
    "She's not far away. She's one consistent season from here.",
    "Borrow confidence from your future self and act on it now.",
    "Build the body, energy, and confidence your future self is counting on.",
    "The woman you'll be in a year starts with the choice you make at lunch.",
    "Future you is real. Treat her like someone worth this effort.",
    "Make decisions today that future you would thank you for through tears of pride.",
    "Your future is not a place you go. It's a person you become.",
    "Send your future self good news through today's habits.",
    "Imagine her, then close the gap by one choice today.",
    "You're always becoming someone. Choose her on purpose.",
    "The best version of you is not a fantasy. She's a schedule.",
    "Plant today what future you wants to harvest.",
    "She's watching, she's proud, and she's asking you to keep going.",
    "Future you is built in the gap between intention and excuse — close it.",

    # --- closing / staying power ---
    "The women who transform are simply the ones who didn't stop.",
    "Outlast the doubt. It always quits before you do, if you let it.",
    "Endurance is the secret nobody sells because it isn't sexy enough.",
    "Stay in the game long enough to win it.",
    "Quitting guarantees the one outcome you don't want.",
    "The finish line moves closer every day you refuse to stop.",
    "Be the woman who was still going when it finally clicked.",
    "Persistence beats talent that gave up.",
    "Keep choosing yourself until it stops feeling like a choice.",
    "The dream isn't far. It's just on the other side of not quitting.",
    "Long-term thinking is the ultimate cheat code.",
    "Stay consistent long enough to surprise yourself.",
    "The only way to lose is to stop. So don't.",
    "Your breakthrough is hiding behind the day you wanted to give up.",
    "Decide that quitting isn't on the menu, and watch what happens.",
    "Slow and steady didn't just win the race. She glowed doing it.",
    "Keep building. The woman you're becoming is worth every quiet day.",
    "You've already proven you can start. Now prove you can stay.",
    "One more day. Then one more. That's how transformations are built.",
    "Keep going — not because it's easy, but because she's worth it.",
]


def message_for_day(day_of_year: int, offset: int = 0) -> str:
    if not MESSAGES:
        return ""
    return MESSAGES[(day_of_year + offset) % len(MESSAGES)]


def today_message(offset: int = 0, now: datetime.date | None = None) -> dict:
    now = now or datetime.date.today()
    doy = now.timetuple().tm_yday
    return {
        "message": message_for_day(doy, offset),
        "date": now.isoformat(),
        "total_messages": len(MESSAGES),
    }
